name: Auto Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip project
      run: zip -r biki-sports.zip .

    - name: Upload to S3
      run: |
        aws s3 cp biki-sports.zip s3://biki-sports-deploy-bucket/biki-sports.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ap-south-1

    - name: Trigger CodeDeploy
      run: |
        aws deploy create-deployment \
        --application-name biki-sports-app \
        --deployment-group-name biki-sports-dg \
        --s3-location bucket=biki-sports-deploy-bucket,key=biki-sports.zip,bundleType=zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ap-south-1

